# Generated by Django 5.0.1 on 2024-01-31 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madaminov', '0002_alter_post_options_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
